# Generated by Django 5.0.1 on 2024-01-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
