# Generated by Django 5.0.1 on 2024-01-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Quantity',
        ),
    ]
